### PR TITLE
Update mne.pick_channels() to mne.pick()

### PR DESCRIPTION
**Pull request by sjg2203**
Update mne.pick_channels() to mne.pick(), as mne.pick_channels() is a legacy function.

I wasn't sure how to deal with the changelog as I only updated mne.pick() which works just like mne.pick_channels().

@raphaelvallat, if you have a moment to review?

### CODE REVIEW

**Review by raphaelvallat — APPROVED** [review]
Thank you! I'll wait for the CI tests to pass and merge. The PR will be included in the release notes of the next stable version. However, I just released a new version of YASA so I don't think there will be another one in the next couple of months.

**Comment by raphaelvallat** [comment]
Unit tests are failing because [pick](https://mne.tools/1.3/generated/mne.io.Raw.html#mne.io.Raw.pick) does not have argument `ordered=`, unlike [pick_channels](https://mne.tools/stable/generated/mne.io.Raw.html#mne.io.Raw.pick_channels):

```
>       raw_pick = raw.copy().pick(ch_names, ordered=True)
E       TypeError: pick() got an unexpected keyword argument 'ordered'
```

Could you verify on your own data that pick returns the channels in the specified order? (e.g. as if using `.pick_channels(..., ordered=True`)

**Comment by sjg2203** [comment]
Just tested it and both returned the same. mne.pick() orders the channels based their order in ```ch_names```.
I removed ```ordered=True``` as it is not available in mne.pick()

> Unit tests are failing because [pick](https://mne.tools/1.3/generated/mne.io.Raw.html#mne.io.Raw.pick) does not have argument `ordered=`, unlike [pick_channels](https://mne.tools/stable/generated/mne.io.Raw.html#mne.io.Raw.pick_channels):
> 
> ```
> >       raw_pick = raw.copy().pick(ch_names, ordered=True)
> E       TypeError: pick() got an unexpected keyword argument 'ordered'
> ```
> 
> Could you verify on your own data that pick returns the channels in the specified order? (e.g. as if using `.pick_channels(..., ordered=True`)

**Comment by raphaelvallat** [comment]
Thank you! Merging now

**Pull request merged**
