### PR TITLE
Updated deprecated functions

### PR DESCRIPTION
**Pull request by sjg2203**
Updated deprecated functions:
- `Series.replace()` to `Series.cat.rename_categories()`
- `pd.Timedelta('S')` to `pd.Timedelta('s')`

### CODE REVIEW

**Comment by sjg2203** [comment]
@raphaelvallat, @remrama if you have a moment to review these changes

**Comment by raphaelvallat** [comment]
Can you please revert the black formatting changes? Can you please also say more about the deprecation, and whether this requires to bump the minimal pandas version? Thanks

**Comment by sjg2203** [comment]
`Series.replace()` was replaced in Pandas 2.1.0 in favor of `Series.cat.rename_categories()`
` pd.Timedelta('S')` was replaced in Pandas 2.2.0 where H, T, S, L, U and N were replaced by h, min, s, ms, us, and ns
It might be wise to bump Pandas version to >=2.2.0

**Review by raphaelvallat — APPROVED** [review]
Approved, thanks!

**Comment by raphaelvallat** [comment]
I'll keep the current dependencies as is for now, and might bump pandas in the future

**Pull request merged**
